# ─────────────────────────────────────────────────────────────────────────────
# Salon AI — training phrases (English + Sinhala Romanized + Natural speech)
# More phrases = better accuracy. Add freely.
# ─────────────────────────────────────────────────────────────────────────────

TRAINING_DATA = {

    "greet": [
        "hello", "hi", "hey", "good morning", "good afternoon", "good evening",
        "hi there", "hello there", "ayubowan", "kohomada", "hello bot",
        "hai", "hii", "heyyy", "yo", "sup", "whats up", "what's up",
        "oba kohomada", "machan", "bro", "hola", "greetings",
        "howdy", "what's good", "hey there", "good day", "morning",
        "evening", "afternoon", "hi bot", "hello zane", "hi zane",
        "start", "begin", "hey ai", "hi ai",
    ],

    "book_appointment": [
        "i want to book", "book appointment", "make appointment",
        "schedule appointment", "i need a booking", "can i book",
        "appointment book karanna", "apointment onei", "book karanna",
        "i want to schedule", "reserve a slot", "get an appointment",
        "appointment hadanna", "appoint karanna", "book a slot",
        "can you book for me", "set an appointment", "i'd like to book",
        "make a reservation", "i want a haircut appointment",
        "appointment ganna", "appoint onei", "book one for me",
        "i want to come in", "want to visit", "coming in for service",
        "book me in", "can i get an appointment", "slot book karanna",
        "api ennam", "ennam", "apu ennam salon ekata",
        "appointment ekak ganna puluwanda", "booking ekak hadanna",
        "i need to come in", "reserve", "fix an appointment",
        "slot ekak ganna", "time ekak ganna", "time fix karanna",
        "appointment danna", "appointment dapan", "book karala danna",
        "haircut book", "facial book", "massage book", "book treatment",
        "want appointment", "need appointment", "appointment please",
        "can i schedule", "i want to see", "i want to visit",
    ],

    "check_services": [
        "what services", "list services", "what do you offer",
        "services list", "show services", "what treatments",
        "monawada karanne", "services monawada", "what can i get",
        "what do you have", "available services", "service katharaya",
        "tell me about services", "services danna", "what are your services",
        "what treatments do you have", "show me what you offer",
        "services show karanna", "service list eka denna",
        "what do you do", "treatment list", "service menu",
        "monawada thiyanawa", "sewa monawada", "services culist",
        "all services", "full service list", "what can i book",
        "what type of services", "services available",
        "haircut service thiyenawada", "facial service thiyenawada",
        "monawada services", "service details", "service info",
        "describe your services", "service catalogue",
    ],

    "check_prices": [
        "how much", "price", "cost", "rate", "charges", "fee",
        "how much does it cost", "what is the price", "pricing",
        "kiyadha", "gana kiya", "price kiyada", "cost kiyada",
        "how much for", "what does it cost", "how much is a",
        "price list", "price chart", "rate card", "service charges",
        "how much is haircut", "facial price", "how much is coloring",
        "eka kiyadha", "gana mokakda", "rates", "fees",
        "how much do you charge", "pricing list", "cost of services",
        "how expensive", "affordable", "cheap", "expensive",
        "pricelist", "tariff", "hakata", "money", "rupees",
        "rs kiyada", "kiyada gana", "gana balanna", "gana danna",
        "how much does haircut cost", "massage gana kiyada",
        "price wada", "price ekata balamu", "service gana",
        "service prices", "all prices", "full price list",
    ],

    "check_availability": [
        "is available", "check availability", "any slots",
        "available time", "free slot", "when can i come",
        "available date", "available nisa", "slot thiyanawada",
        "is there a slot", "when is free", "any opening",
        "can i come tomorrow", "time slot", "opening available",
        "check slot", "available appointment", "free time",
        "koheda free", "koheda available", "opening innawada",
        "availability check", "when are you free", "openings",
        "do you have space", "is there room", "any availability",
        "free slot thiyenawada", "time available",
        "tomorrow free nisa", "saturday available nisa",
        "when can i get in", "earliest available",
        "next available slot", "open slots",
    ],

    "check_branches": [
        "where are you", "location", "branch", "address",
        "where is the salon", "which branch", "branches",
        "where located", "salon location", "find you",
        "koheda inne", "address danna", "location danna",
        "how many branches", "branch list", "where to find",
        "directions", "how to get there", "map",
        "nearest branch", "closest location", "near me",
        "where is zane salon", "zane salon koheda",
        "branches thiyanawa", "locations", "outlets",
        "salon address", "where to go", "how to visit",
        "salon innawa koheda", "branch eka koheda",
        "find nearest", "locate branch", "branch details",
    ],

    "check_staff": [
        "who is available", "staff", "stylist", "hairdresser",
        "who can i see", "available staff", "who works there",
        "staff list", "who are the stylists", "any good stylist",
        "staff thiyanawada", "stylist innawada", "who is working",
        "recommended staff", "best stylist", "who should i book",
        "staff danna", "people working", "team",
        "who is the best", "good hairdresser", "expert stylist",
        "skilled staff", "experienced stylist",
        "staff members", "beauticians", "therapists",
        "who is on duty", "staff on duty", "barber",
        "hairstylist", "beauty therapist",
        "staff show karanna", "team members",
        "staff info", "about staff", "stylists list",
        "kenekuta book karanna", "which stylist",
    ],

    "cancel_appointment": [
        "cancel appointment", "cancel booking", "i want to cancel",
        "remove my appointment", "delete booking", "cancel my slot",
        "appointment cancel karanna", "cancel karanna", "nothung",
        "i need to cancel", "please cancel", "cancel it",
        "don't want appointment", "cancel the booking",
        "reschedule", "change appointment", "move appointment",
        "appointment change karanna", "different time", "postpone",
        "cancel my reservation", "remove booking",
    ],

    # ── Management intents ────────────────────────────────────────────────
    "today_appointments": [
        "how many appointments today", "today appointments", "today schedule",
        "appointments today", "today's bookings", "how many bookings today",
        "ada appointments", "ada bookings", "ada schedule",
        "what appointments do we have today", "show today appointments",
        "today appointment count", "how busy are we today",
        "todays appointments", "schedule for today",
        "ada kiyada appointments", "ada kiyada bookings",
        "ada hama appointments", "appointments list",
        "show me today", "today's agenda", "daily schedule",
        "who is coming today", "customers today",
        "ada enna ona minissu", "ada apu kiyada", "ada schedule eka",
        "today's list", "appointment list today", "today check",
    ],

    "pending_appointments": [
        "pending appointments", "unconfirmed bookings", "pending bookings",
        "how many pending", "show pending", "not confirmed appointments",
        "waiting appointments", "approval pending", "pending list",
        "confirm karana na appointments", "pending ona",
        "which appointments are pending", "unconfirmed",
        "not yet confirmed", "need to confirm", "confirm karanna tiyena",
        "pending bookings list", "appointments to confirm",
        "confirm karanna balanawa", "unverified bookings",
        "outstanding appointments", "pending count",
        "kiyada pending", "confirm karanna ona",
    ],

    "today_revenue": [
        "today revenue", "today's earnings", "how much earned today",
        "today income", "today sales", "today's money",
        "ada revenue", "ada income", "ada earnings", "ada sales",
        "how much did we make today", "daily revenue", "today total",
        "today payment total", "today collection",
        "ada kiyada income", "ada kiyada wada una",
        "today's takings", "daily takings", "today's profit",
        "money earned today", "how much collected today",
        "revenue for today", "today's figures", "today turnover",
        "ada laba", "ada income kiyada", "today money",
        "how much money today", "ada total ekak kiyada",
    ],

    "staff_stats": [
        "staff performance", "best staff", "top staff", "who is best staff",
        "staff report", "staff stats", "staff commission",
        "who performed best", "top performing staff",
        "staff ranking", "staff revenue", "which staff is best",
        "staff veda", "staff performance report",
        "who did the most work", "hardest working staff",
        "staff leaderboard", "staff productivity",
        "best employee", "top employee", "who earned most",
        "who did most appointments", "staff summary",
        "employee performance", "staff monthly report",
        "staff this month", "best this month",
        "kaurutha best", "staff list with performance",
        "staff contribution", "team performance",
    ],

    "low_inventory": [
        "low stock", "inventory alert", "what is low", "low inventory",
        "out of stock", "stock running low", "inventory warning",
        "stock check", "what needs restocking", "low items",
        "stock thibena dewal", "stock nathi", "inventory low",
        "what products are running out", "reorder needed",
        "stock status", "inventory status", "check inventory",
        "what's running out", "products low", "supplies low",
        "inventory check", "what to reorder",
        "stock nearly empty", "almost out of",
        "thibena stock", "stock eka balanna", "nathi wela",
        "stocking needed", "supply alert",
    ],

    "walkin_status": [
        "walk in queue", "walkin queue", "how many walk ins",
        "walk in count", "queue status", "current queue",
        "who is waiting", "walk in today", "walk-in list",
        "ada walk in", "queue eka kohomada", "walkin status",
        "how many people waiting", "queue length",
        "waiting list", "who is in queue", "current wait",
        "people waiting", "walk-ins today",
        "ada walked in kiyada", "queue check",
        "waiting customers", "how long is queue",
        "walk ins now", "walkin today count",
        "queue ekak thiyenawada", "minissu innawa kiyada",
    ],

    "customer_stats": [
        "how many customers", "total customers", "customer count",
        "customer stats", "new customers", "customer report",
        "customers this month", "customer total",
        "customers thiyanawa", "customer gana", "how many clients",
        "total clients", "customer database",
        "customer base", "how many people", "client count",
        "registered customers", "customer list",
        "new registrations", "new clients this month",
        "customer growth", "total registered",
        "ada customers kiyada", "monthly customers",
        "active customers", "loyal customers",
    ],

    "recent_payments": [
        "recent payments", "latest payments", "last payments",
        "today payments", "payment list", "recent transactions",
        "show payments", "recent sales", "latest transactions",
        "ada payments", "recent bills", "payment history",
        "last few payments", "what was paid today",
        "transactions today", "today's transactions",
        "who paid today", "payment records",
        "recent collections", "last payments received",
        "ada pay kala minissu", "payment summary today",
        "recent receipts", "today bills",
    ],

    "goodbye": [
        "bye", "goodbye", "see you", "thanks bye", "ok thanks",
        "thank you bye", "later", "cya", "take care", "done",
        "ok done", "that's all", "nothing else", "thats it",
        "thank you", "thanks", "ok thank you", "cheers",
        "istuti", "bohoma istuti", "gihin ennam", "ok gihin ennam",
        "have a good day", "farewell", "au revoir", "adios",
        "ttyl", "talk later", "all good thanks", "all done",
        "finished", "done for now", "that's everything",
        "ok bye", "bye bye", "tata", "laters",
    ],

    "help": [
        "help", "what can you do", "how does this work",
        "i need help", "assist me", "guide me", "confused",
        "what to do", "options", "menu", "commands",
        "help karanna", "help eka denna", "explain",
        "how to use", "what can i ask", "what do you know",
        "capabilities", "features", "what are you able to do",
        "show me what you can do", "what questions can i ask",
        "instructions", "guidance", "tutorial",
        "how to chat", "bot help", "ai help",
        "monawada kiyanna puluwang", "mokak karanna puluwang",
        "what should i say", "what to type",
        "available commands", "command list",
    ],
}
